openapi: 3.0.1
info:
  title: forward
  description: API Definition of forward
  version: 1.0.0
servers:
- url: http://localhost:8290/forward
paths:
  /:
    post:
      responses:
        default:
          description: Default response
